apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mysql
  namespace: mysql-cluster
spec:
  secretName: mypwds
  instances: 3
  router:
    instances: 1
  backupProfiles:
  - name: dump-instance-profile-pvc
    dumpInstance:
      storage:
        persistentVolumeClaim:
          claimName: backup-volume-claim-1
  - name: dump-instance-profile-oci
    dumpInstance:
      storage:
        ociObjectStorage:
          prefix : /
          bucketName: idbcluster_backup
          credentials: oci-credentials 
